name: shelve
description: "A safe hub to store important things"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  dataform: ^1.1.1
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 800
    - family: iconcino
      fonts:
        - asset: assets/fonts/iconcino.ttf