import 'package:flutter/material.dart';

class LightTheme {
  static ThemeData get theme => ThemeData(
        useMaterial3: false,
        primaryColor: const Color(0xff4866FA),
        primaryColorDark: const Color(0xff3F5AE1),
        primaryColorLight: const Color(0xff6A85FF),
        brightness: Brightness.light,
        scaffoldBackgroundColor: const Color(0xffFCFCFC),
        disabledColor: const Color(0xff666666),
        dividerColor: const Color(0xffE8E8E8),
        cardColor: const Color(0xffFFFFFF),
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff4866FA),
          primaryContainer: Color(0xffDCE1FC),
          onPrimary: Color(0xffFFFFFF),
          secondary: Color(0xff55D6BE),
          onSecondary: Color(0xff191919),
          error: Color(0xffef233c),
          onError: Color(0xffFFFFFF),
          background: Color(0xffFCFCFC),
          onBackground: Color(0xff191919),
          surface: Color(0xffFFFFFF),
          onSurface: Color(0xff191919),
          surfaceVariant: Color(0xffF6F6F6),
          onSurfaceVariant: Color(0xff4F4F57),
        ),
        textTheme: const TextTheme(
          displayLarge: TextStyle(
            fontSize: 48,
            fontWeight: FontWeight.w600,
            height: 1.12,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          displayMedium: TextStyle(
            fontSize: 36,
            fontWeight: FontWeight.w600,
            height: 1.16,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          displaySmall: TextStyle(
            fontSize: 30,
            fontWeight: FontWeight.w600,
            height: 1.22,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          headlineLarge: TextStyle(
            fontSize: 48,
            fontWeight: FontWeight.w600,
            height: 1.25,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          headlineMedium: TextStyle(
            fontSize: 36,
            fontWeight: FontWeight.w400,
            height: 1.29,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          headlineSmall: TextStyle(
            fontSize: 30,
            fontWeight: FontWeight.w800,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          titleLarge: TextStyle(
            fontSize: 36,
            fontWeight: FontWeight.w600,
            height: 1.27,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          titleMedium: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.w800,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          titleSmall: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w500,
            height: 1.43,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          labelLarge: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            height: 1.43,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          labelMedium: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w500,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          labelSmall: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w500,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          bodyLarge: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w800,
            height: 1.50,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          bodyMedium: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w500,
            height: 1.15,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
          bodySmall: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 1.15,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Sora',
          ),
        ).apply(
          bodyColor: const Color(0xff191919),
          displayColor: const Color(0xff191919),
        ),
      );
}
